services:
  - type: web
    name: streambox-api
    runtime: docker
    region: frankfurt
    plan: free
    repo: https://github.com/Drake-70/StreamBox-App
    branch: main
    dockerfilePath: backend/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: CAMPAY_MODE
        sync: false
      - key: CAMPAY_APP_USERNAME
        sync: false
      - key: CAMPAY_APP_PASSWORD
        sync: false
      - key: CAMPAY_ENVIRONMENT
        sync: false
      - key: SYNC_CRON
        value: "0 3 * * *"
      - key: SYNC_TIMEZONE
        value: "Africa/Douala"
      - key: EXPIRY_CRON
        value: "0 * * * *"
    autoDeploy: true
